# Generated by Django 6.0.6 on 2026-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='notion_budget', max_length=50)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], max_length=10)),
                ('synced_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_page_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
