# Generated by Django 6.0.6 on 2026-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='カンマ区切り 例: Django, Python', max_length=200)),
                ('repo_url', models.URLField(blank=True)),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
