# Generated by Django 6.0.6 on 2026-07-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='body',
            field=models.TextField(blank=True, help_text='Markdown記法で本文を書けます'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_covers/'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='learninglog',
            name='description',
            field=models.TextField(help_text='一覧ページに表示する短い要約'),
        ),
    ]
