# Generated by Django 6.0.6 on 2026-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learninglog_body_learninglog_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True, help_text='RSSのdescriptionをそのまま保存')),
                ('category', models.CharField(choices=[('experience', '経験談'), ('personal', '個人開発'), ('team', 'チーム開発')], default='personal', help_text='noteの記事に付けたハッシュタグから自動判定', max_length=20)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='LearningLog',
        ),
    ]
