# Generated by Django 6.0.6 on 2026-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notearticle_delete_learninglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notearticle',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='noteのサムネイル画像URL'),
        ),
        migrations.AlterField(
            model_name='notearticle',
            name='summary',
            field=models.TextField(blank=True, help_text='HTMLタグを除去したプレーンテキストで保存'),
        ),
    ]
